services:
  walletkit:
    image: waltid/walletkit:latest
    command:
      - run
    environment:
      WALTID_DATA_ROOT: /waltid-walletkit/data-root
      WALTID_WALLET_BACKEND_BIND_ADDRESS: 0.0.0.0
    volumes:
      - ./walletkit:/waltid-walletkit/data-root # data store volume incl. config files.
    ports:
      - 8080:8080
  api:
    build: ./api
    ports:
      - 8081:3000